--- 
title: "MyBook"
author: "Corinna Trierweiler and Philipp Gaulke"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: report
description: "This is a guide for data science with R"
---

# Preface {-}

"Data is the sword of the 21st century, those who wield it well, the Samurai." Jonathan Rosenberg, adviser to Larry Page and former SVP of products at Google. 
This book has been produced for and based on the Data Science for Business class of Hochschule Fresenius in Cologne, Germany. In context of the task, the book includes basic R skills, statistical methods for data science and a own project is fulfilled. 
The majority of information used in this book are learned in the lessons in class. Especially, lecture notes have been the basis for the book. Besides this, the online sources  tidyverse.com and the book of David Dalpiaz have been used as reference. 

This book can serve as a source for all people who are interested in studying R and statistic models. 


```{r, include=FALSE}

require(magrittr)
require(tidyverse)
require(ISLR)
require(gbm)
require(caret)
require(FNN)
require(rpart)
require(boot)
require(forcats)
require(lattice)
require(stringr)
require(tibble)
require(ellipse)
require(metrics)
require(GGally)
require(tidyr)
require(ggplot2)
require(dplyr)
require(readr)

```