---
title: "13_Solution_Task_a2_Polynomials"
author: "PGaulke"
date: "28 Juli 2019"
output: html_document
---

```{r, include=FALSE}

# to get prepared
require(tidyverse)
require(ISLR)
require(magrittr)


load("C:/Users/admin/Dropbox/Master/2. Semester/Data Science/MyBook/project_data.Rdata")
summary(train.data)
summary(test.data)

# 11 variables for frequency of seven plants
# task: The test.data has the same structure but does not contain the frequencies for each of the 7 plants. Your
# goal is precisely to estimate them for the 140 observations

# variables:character to numeric
# for train.data
train.data$season = as.numeric(c("spring" = "1", "summer" = "2", "autumn" = "3", "winter" = "4")[train.data$season])

train.data$size = as.numeric(c("small" = "1", "medium" = "2", "large" = "3")[train.data$size])

train.data$speed = as.numeric(c("low" = "1", "medium" = "2", "high" = "3")[train.data$speed])


# for test.data

test.data$season = as.numeric(c("spring" = "1", "summer" = "2", "autumn" = "3", "winter" = "4")[test.data$season])

test.data$size = as.numeric(c("small" = "1", "medium" = "2", "large" = "3")[test.data$size])

test.data$speed = as.numeric(c("low" = "1", "medium" = "2", "high" = "3")[test.data$speed])


# delete na
#is.na(train.data)
#na.omit(train.data)

# replace missing value with the mean (and avoid a loop!)

train.data$mxPH[is.na(train.data$mxPH)] <- round(mean(train.data$mxPH, na.rm = TRUE))
train.data$mnO2[is.na(train.data$mnO2)] <- round(mean(train.data$mnO2, na.rm = TRUE))
train.data$Cl[is.na(train.data$Cl)] <- round(mean(train.data$Cl, na.rm = TRUE))
train.data$NO3[is.na(train.data$NO3)] <- round(mean(train.data$NO3, na.rm = TRUE))
train.data$NH4[is.na(train.data$NH4)] <- round(mean(train.data$NH4, na.rm = TRUE))
train.data$oPO4[is.na(train.data$oPO4)] <- round(mean(train.data$oPO4, na.rm = TRUE))
train.data$PO4[is.na(train.data$PO4)] <- round(mean(train.data$PO4, na.rm = TRUE))
train.data$Chla[is.na(train.data$Chla)] <- round(mean(train.data$Chla, na.rm = TRUE))

# to to the same with the test.data
test.data$mxPH[is.na(test.data$mxPH)] <- round(mean(test.data$mxPH, na.rm = TRUE))
test.data$mnO2[is.na(test.data$mnO2)] <- round(mean(test.data$mnO2, na.rm = TRUE))
test.data$Cl[is.na(test.data$Cl)] <- round(mean(test.data$Cl, na.rm = TRUE))
test.data$NO3[is.na(test.data$NO3)] <- round(mean(test.data$NO3, na.rm = TRUE))
test.data$NH4[is.na(test.data$NH4)] <- round(mean(test.data$NH4, na.rm = TRUE))
test.data$oPO4[is.na(test.data$oPO4)] <- round(mean(test.data$oPO4, na.rm = TRUE))
test.data$PO4[is.na(test.data$PO4)] <- round(mean(test.data$PO4, na.rm = TRUE))
test.data$Chla[is.na(test.data$Chla)] <- round(mean(test.data$Chla, na.rm = TRUE))

```

```{r, include=FALSE, eval= FALSE}
#create test data
set.seed(200)
num_obs = nrow(train.data)

train.index = sample(num_obs, size = trunc(0.50 * num_obs))
newtrain.data = train.data[train_index, ]
traintest.data = train.data[-train_index, ]


# replace again missing valuesith the mean (and avoid a loop!)

newtrain.data$mxPH[is.na(newtrain.data$mxPH)] <- round(mean(newtrain.data$mxPH, na.rm = TRUE))
newtrain.data$mnO2[is.na(newtrain.data$mnO2)] <- round(mean(newtrain.data$mnO2, na.rm = TRUE))
newtrain.data$Cl[is.na(newtrain.data$Cl)] <- round(mean(newtrain.data$Cl, na.rm = TRUE))
newtrain.data$NO3[is.na(newtrain.data$NO3)] <- round(mean(newtrain.data$NO3, na.rm = TRUE))
newtrain.data$NH4[is.na(newtrain.data$NH4)] <- round(mean(newtrain.data$NH4, na.rm = TRUE))
newtrain.data$oPO4[is.na(newtrain.data$oPO4)] <- round(mean(newtrain.data$oPO4, na.rm = TRUE))
newtrain.data$PO4[is.na(newtrain.data$PO4)] <- round(mean(newtrain.data$PO4, na.rm = TRUE))
newtrain.data$Chla[is.na(newtrain.data$Chla)] <- round(mean(newtrain.data$Chla, na.rm = TRUE))

# to to the same with the new test.data
traintest.data$mxPH[is.na(traintest.data$mxPH)] <- round(mean(traintest.data$mxPH, na.rm = TRUE))
traintest.data$mnO2[is.na(traintest.data$mnO2)] <- round(mean(traintest.data$mnO2, na.rm = TRUE))
traintest.data$Cl[is.na(traintest.data$Cl)] <- round(mean(traintest.data$Cl, na.rm = TRUE))
traintest.data$NO3[is.na(traintest.data$NO3)] <- round(mean(traintest.data$NO3, na.rm = TRUE))
traintest.data$NH4[is.na(traintest.data$NH4)] <- round(mean(traintest.data$NH4, na.rm = TRUE))
traintest.data$oPO4[is.na(traintest.data$oPO4)] <- round(mean(traintest.data$oPO4, na.rm = TRUE))
traintest.data$PO4[is.na(traintest.data$PO4)] <- round(mean(traintest.data$PO4, na.rm = TRUE))
traintest.data$Chla[is.na(traintest.data$Chla)] <- round(mean(traintest.data$Chla, na.rm = TRUE))
summary(newtrain.data)
summary(traintest.data)
```



#  Developing a Model for a2 - Polynomials

```{r}

# test it first

testpolymod <- glm(a2 ~ season + size + speed + mxPH + mnO2 + Cl + NO3 + NH4 + oPO4 + PO4 + Chla, data=newtrain.data)
summary(testpolymod)
# deleting variables with lowest significance

testpolymod2 <- lm(a2 ~ speed + mxPH + Chla, data=newtrain.data)
summary(testpolymod2)

# use of poly

testpolymod3 <- lm(a2 ~ poly(Chla,3)+ poly(speed,2) + poly(mxPH,2), data=newtrain.data)
summary(testpolymod3)

# adjust

testpolymod4 <- lm(a2 ~ poly(Chla,2), data=newtrain.data)
summary(testpolymod4)

# looks not too good, but continue with poly to evaluate the method

test.pred.polymod <- predict(testpolymod4,traintest.data) 
 
RMSE.polymod <- sqrt(mean((test.pred.polymod-traintest.data$a4)^2))
RMSE.polymod

MAE.polymod <- mean(abs(test.pred.polymod-traintest.data$a4))
MAE.polymod

# in this case it is actually not helping to use polynomials compared to regular mlr
# this might need to be tested individually on each response 

```


```{r}

polymod <- glm(a2 ~ season + size + speed + mxPH + mnO2 + Cl + NO3 + NH4 + oPO4 + PO4 + Chla, data=train.data)
summary(polymod)
# deleting variables with lowest significance

polymod2 <- lm(a2 ~ speed + mxPH + Chla, data=train.data)
summary(polymod2)

# use of poly

polymod3 <- lm(a2 ~ poly(Chla,2, data=train.data)
summary(polymod3)

a2pred <- predict(polymod3,test.data)
summary(a2pred)

```

Try to put Chla (only) poly in a graph
```{r}

fita2 <- lm(a2 ~ poly(Chla,3), data=train.data )
summary(fita2)

fita3 <- lm(a2 ~ poly(Chla,2), data=train.data )
summary(fita3)

fita4 <- lm(a2 ~ Chla, data=train.data )
summary(fita4)

# poly just on Chla

train.data <- train.data %>%
	mutate(fit1 = predict(fita2),
	fit2 = predict(fita3),
	fit5 = predict(fita4))

cols <- c("Deg.3", "Deg.2", "Deg.1")
train.data %>% 
	ggplot(aes(x=a2, y=Chla)) +
	geom_point() +
	geom_line(aes(y=fit1, color="Deg.3"), size =1) +
	geom_line(aes(y=fit2, color="Deg.2"), size =1) +
	geom_line(aes(y=fit5, color="Deg.1"), size =1) +
	theme(legend.title = element_blank(), 
		legend.position = "bottom", 
		legend.direction = "horizontal")

```

