---
title: "16_Solution_SLR"
author: "PGaulke"
date: "26 Juli 2019"
output: html_document
---

# Method SLR

```{r}
# To prepare for the fight
require(tidyverse)
require(ISLR)
require(magrittr)


load("C:/Users/admin/Dropbox/Master/2. Semester/Data Science/MyBook/project_data.Rdata")

summary(train.data)
summary(test.data)

# delete the N/A
is.na(train.data)
na.omit(train.data)
# 11 variables for frequency of seven plants
# task: The test.data has the same structure but does not contain the frequencies for each of the 7 plants. Your
# goal is precisely to estimate them for the 140 observations


```


```{r, eval=FALSE}
plot(mxPH ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "mxPH vs a1")
plot(mnO2 ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "mnO2 vs a1")
plot(Cl ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "Cl vs a1")
plot(NO3 ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "NO3 vs a1")
plot(NH4 ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "NH4 vs a1")
plot(oPO4 ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "oPO4 vs a1")
plot(PO4 ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "PO4 vs a1")
plot(Chla ~ a1, data = train.data, col = "dodgerblue", pch = 20, cex = 1.5,
     main = "Chla vs a1")

#tendenziell mehr mxPH und mnO2

pairs(train.data)

```

```{r}

ggplot(train.data, aes(x = a1, y = NO3)) +
  geom_point() +
  stat_smooth()




model.slr <- lm(a1 ~ NO3, data = train.data)
summary(model.slr)

#model.slr$fitted.values
#model.slr$coefficients



```

```{r}

lmod <- lm(a1 ~ NO3, data=newtrain.data)
a1pred <- predict(lmod, traintest.data)

summary(lmod)
summary(a1pred)

actuals_pred <- cbind(actuals=traintest.data$a1, predicteds=a1pred)

correlation_accuracy<- cor(actuals_pred)
head(actuals_pred)
```

```{r}
lm1 <- lm(a1 ~ mxPH, data=newtrain.data)
summary(lm1)
pred1<-predict(lm1, traintest.data)
pred1

RSS1 <- sum((traintest.data$a1 -  predict(lm1))^2)
RSS1


lm2 <- lm(a1 ~ mnO2, data=newtrain.data)
summary(lm2)
pred2<-predict(lm2, traintest.data)
pred2

RSS2 <- sum((traintest.data$a1 -  predict(lm2))^2)
RSS2


lm3 <- lm(a1 ~ Cl, data=newtrain.data)
summary(lm3)
pred3<-predict(lm3, traintest.data)
pred3

RSS3 <- sum((traintest.data$a1 -  predict(lm3))^2)
RSS3


lm4 <- lm(a1 ~ NO3, data=newtrain.data)
summary(lm4)
pred4<-predict(lm4, traintest.data)
pred4

RSS4 <- sum((traintest.data$a1 -  predict(lm4))^2)
RSS4


lm5 <- lm(a1 ~ NH4, data=newtrain.data)
summary(lm5)
pred5<-predict(lm5, traintest.data)
summary(pred5)

RSS5 <- sum((traintest.data$a1 -  predict(lm5))^2)
RSS5


lm6 <- lm(a1 ~ oPO4, data=newtrain.data)
summary(lm6)
pred6<-predict(lm6, traintest.data)
pred6

RSS6 <- sum((traintest.data$a1 -  predict(lm6))^2)
RSS6


lm7 <- lm(a1 ~ PO4, data=newtrain.data)
summary(lm7)
pred7<-predict(lm7, traintest.data)
pred7

RSS7 <- sum((traintest.data$a1 -  predict(lm7))^2)
RSS7

lm8 <- lm(a1 ~ Chla, data=newtrain.data)
summary(lm8)
pred8<-predict(lm8, traintest.data)
pred8


RSS8 <- sum((traintest.data$a1 -  predict(lm8))^2)
RSS8

```

library("ggplot2")
p <- ggplot(actuals_pred, aes(actuals, predicteds)) +
  geom_point() +
  stat_smooth(method = lm)
# 3. Add prediction intervals
p + geom_line(aes(y = actuals), color = "red", linetype = "dashed")+
    geom_line(aes(y = predicteds), color = "red", linetype = "dashed")



```
